### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Abdulkadir98**
Added a non-profit android application

### CODE REVIEW

**Comment by esoxjem** [comment]
Hi @Abdulkadir98, this looks really awesome. I just want to point out that MyChild app is a for-profit org as mentioned in the video, so please add it the for-profit section :)

**Comment by Abdulkadir98** [comment]
Oh I must have missed that out, I'll do that, thanks!

**Review by Abdulkadir98 — COMMENTED** [review]
Added mychild App under for-profit category.

**Comment by esoxjem** [comment]
@Abdulkadir98 Thanks. Would be great if you could tweet about this contribution quoting my original tweet. That way I can retweet it and we'll have more reach :)
https://twitter.com/_arunsasi/status/1052621172062466048

**Comment by Abdulkadir98** [comment]
Done :D

**Pull request merged**
